[package]
name = "inkview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.1"

[features]
default = ["sdk-6-5"]
sdk-5-19 = []
sdk-6-5 = []
